#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "possible-x-edc.fullname" . }}
  labels:
    {{- include "possible-x-edc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.web.http.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.web.http.management.port }}
      protocol: TCP
      name: management
    - port: {{ .Values.service.protocolPort }}
      targetPort: {{ .Values.web.http.protocol.port }}
      protocol: TCP
      name: protocol
    - port: {{ .Values.service.publicPort }}
      targetPort: {{ .Values.web.http.public.port }}
      protocol: TCP
      name: public
    - port: {{ .Values.service.controlPort }}
      targetPort: {{ .Values.web.http.control.port }}
      protocol: TCP
      name: control
  selector:
    {{- include "possible-x-edc.selectorLabels" . | nindent 4 }}
