name: Deploy Provider
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
env:
  REGISTRY: ghcr.io
  NAMESPACE: possible-x
  PROVIDER_DEPLOYMENT_NAME: dev-provider-possible-x-edc
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: 'Create Secret'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: "create secret docker-registry github-registry-auth -n ${{ vars.PROVIDER_NS }} --docker-server=https://${{env.REGISTRY}} --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }} --docker-email=admin@possible-x.de"

      - name: 'Deploy'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: "set image deployment/${{env.PROVIDER_DEPLOYMENT_NAME}} -n ${{ vars.PROVIDER_NS }} possible-x-edc=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/connector:${{ github.sha }} "
