name: Deploy Provider
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
env:
  REGISTRY: ghcr.io
  NAMESPACE: possible-x
  PROVIDER_DEPLOYMENT_NAME: dev-provider-possible-x-edc
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: "set image deployment/${{env.PROVIDER_DEPLOYMENT_NAME}} possible-x-edc=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/connector:${{ github.sha }} "
