name: Deploy Provider
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1.7.0'
        with:
          token: '${{ github.token }}'
          chart: 'app'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

